### ISSUE TITLE
Fix timestamp error in chat

### ISSUE THREAD

**Issue by dleunji** [gausstalk/gausstalk-backend#65]
<img width="216" alt="스크린샷 2022-09-06 오전 12 32 24" src="https://user-images.githubusercontent.com/46207836/188482388-9a2eb944-bf15-4a8a-a50d-be5e9cf51800.png">
Sometimes timestamp disappear in chat regardless of GIF feature that I'm developing.

**Comment by yonsweng** [comment]
Isn’t it intended? If the same time, then it doesn’t show it.
